OurMusic/Models/Room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.People = new HashSet<Person>();
            this.Songs = new HashSet<Song>();
        }
    
        public System.Guid roomid { get; set; }
        public bool isPrivate { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> administrator { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}

OurMusic/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OurMusic.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;
using OurMusic.Hubs;

namespace OurMusic.Controllers
{
    public class RoomController : Controller
    {
        private OurMusicEntities db = new OurMusicEntities();
        public static UserManager<ApplicationUser> umanager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        private string LOGGEDIN_USER;
        private IHubContext _context = GlobalHost.ConnectionManager.GetHubContext<RoomHub>();
        // GET: /Room/
        public async Task<ActionResult> Index()
        {
            var rooms = db.Rooms.Include(r => r.Person);
            return View(await rooms.ToListAsync());
        }

        private Person getLoggedInPerson()
        {
            ApplicationUser user = umanager.FindById(User.Identity.GetUserId());
            var person = db.People.Where(x => x.userName == user.UserName).FirstOrDefault();
            return person;
        }

        // GET: /Room/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = await db.Rooms.FindAsync(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            ViewBag.Room = room;
            ViewBag.Person = getLoggedInPerson();
            return View(room);
        }

        // GET: /Room/Create
        public ActionResult Create()
        {
            ViewBag.administrator = new SelectList(db.People, "userID", "firstName");
            return View();
        }

        // POST: /Room/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="roomid,isPrivate,name,administrator")] Room room)
        {
            if (ModelState.IsValid)
            {
                room.roomid = Guid.NewGuid();
                db.Rooms.Add(room);
                await db.SaveChangesAsync();
                var roomtest = db.Rooms.Where(x => x.roomid == room.roomid).FirstOrDefault();
                roomtest.People.Add(getLoggedInPerson());
                roomtest.administrator = getLoggedInPerson().userID;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = room.roomid });
            }

            ViewBag.administrator = new SelectList(db.People, "userID", "firstName", room.administrator);
            return RedirectToAction("Details", new { id = room.roomid });
        }

        // GET: /Room/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = await db.Rooms.FindAsync(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            ViewBag.administrator = new SelectList(db.People, "userID", "firstName", room.administrator);
            return View(room);
        }

        // POST: /Room/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="roomid,isPrivate,name,administrator")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.administrator = new SelectList(db.People, "userID", "firstName", room.administrator);
            return View(room);
        }

        // GET: /Room/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = await db.Rooms.FindAsync(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: /Room/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Room room = await db.Rooms.FindAsync(id);

            string roomName = room.name;
            var users = db.People.Where(x => x.activeRoom == room.roomid);
            foreach (var user in users)
                user.activeRoom = null;

            await db.SaveChangesAsync();

            db.Rooms.Remove(room);
            await db.SaveChangesAsync();
            RoomHub.alertRoomHasBeenDeleted(roomName);
            return RedirectToAction("Index");
        }

        // GET: /Room/Join/5
        public async Task<ActionResult> Join(Guid personid,Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = await db.Rooms.FindAsync(id);
            Person person = await db.People.FindAsync(personid);
            room.People.Add(person);
            await db.SaveChangesAsync();
            if (room == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Details", new {id=id});
        }

        // GET: /Room/Leave/5
        public async Task<ActionResult> Leave(Guid personid, Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = await db.Rooms.FindAsync(id);
            Person person = await db.People.FindAsync(personid);
            room.People.Remove(person);
            await db.SaveChangesAsync();
            if (room == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OurMusic/Views/Room/Create.cshtml
@using OurMusic.Models
@model OurMusic.Models.Room
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Room</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="form-group">
                <label class="control-label col-md-2" for="name">Name</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name)
                    @Html.ValidationMessageFor(model => model.name)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="isPrivate">Is this room private?</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.isPrivate)
                    @Html.ValidationMessageFor(model => model.isPrivate)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OurMusic/Views/Room/Delete.cshtml
@model OurMusic.Models.Room

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.isPrivate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isPrivate)
        </dd>

        <dt>
            room @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            admin @Html.DisplayNameFor(model => model.Person.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.firstName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OurMusic/Views/Room/Details.cshtml
@using OurMusic.Models
@model OurMusic.Models.Room

@{
    ViewBag.Title = "Details";
        
    String admin = ViewBag.Room.administrator.ToString();
    String id = ViewBag.Person.userID.ToString();
    String roomID = ViewBag.Room.roomid.ToString();
    String username = ViewBag.Person.userName.ToString();
    String firstName = ViewBag.Person.firstName.ToString();
    String lastName = ViewBag.Person.lastName.ToString();
}
<head>
    <title>Room</title>
    <!-- For testing-->
    <link href="~/Content/qunit-1.18.0.css" rel="stylesheet" />
</head>

@if (@admin == @id)
{
    <input type="hidden" id="isAdmin" value="admin" />
}
else
{
    <input type="hidden" id="isAdmin" value="no" />
}
<input type="hidden" id="currentID" value="@id" />
<input type="hidden" id="adminID" value="@admin" />
<input type="hidden" id="firstName" value="@firstName" />
<input type="hidden" id="lastName" value="@lastName" />

@if (@admin == @id)
{
    @Html.ActionLink("DELETE ROOM", "Delete", "Room", new { id = ViewBag.Room.roomid }, new { })
}

<div class="row">
    <center><h1 id="roomName">@Model.name</h1></center>
    <div class="col-lg-4">
        <h3>People</h3>
        <div class="panel panel-primary">
               <div class="panel-body" style="max-height: 300px; overflow-y: scroll;">  
                   <ul class="list-group" id="userList">
                        @foreach(var x in Model.People)
                        { 
                        <li id="@x.userID" class="list-group-item">@x.firstName @x.lastName
                        @if(Model.administrator == x.userID)
                        {
                            <i>(Administrator)</i>
                        }
                        else if (@admin == @id)
                        {
                            <span class="glyphicon glyphicon-remove removeUser" data-userID="@x.userID" style="float:right;color:red"></span>
                        }
                         </li>
                        }
                    </ul>
                </div>
        </div>
    </div>
    <div class="col-lg-8">
        <div id="player"></div>
    </div>
</div>

<div class="row">
    <div class="col-xs-6"></div>
    <div class="col-xs-6">
        <h3>Add Songs to Queue</h3>
        <ul class="list-group">
            @foreach (var x in Model.Songs)
            {
                <li class="list-group-item">@x.songId,@x.songURL</li>
            }
        </ul>
    </div>
</div>

<div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <input type="text" id="searchQuery" placeholder="Enter Search Query Here" size="35" /><br />
        <button id="searchButton">Search Video</button><br />
        <font color="red" id="searchError"></font>
        <br />
    </div>
    <div class="col-md-4">
        <input type="text" id="vidTitle" placeholder="Video Title" size="35" disabled /><br />
        <input type="text" id="vidUrl" placeholder="Video URL" size="35" disabled />
        <input type="button" id="addVideo" value="Add To Queue" disabled /><br />
    </div>
        <div class="panel-body" style="max-height: 300px; overflow-y: scroll;">
            <table id="queueList" class="table">
                <thead id="tableHeader">
                    <tr id="titleRow">
                        <th>Video Title</th>
                        <th>Video URL</th>
                        <th>Votes</th>
                        <th>Upvote</th>
                        <th>Downvote</th>
                        @if (@admin == @id)
                        {
                            <th>Delete</th>
                        }
                    </tr>
                </thead>
                <tbody id="tbd"></tbody>
            </table>
        </div>
</div>

<h3>Chat</h3>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>

<script src="/Scripts/jquery-2.1.3.min.js"></script>
<script src="/Scripts/jquery.signalR-2.2.0.js"></script>
<script src="/signalr/hubs"></script>
<script src="/Scripts/room.js"></script>

<script type="text/javascript">
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    var player;
    var time;

    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '390',
            width: '640',
            videoId: 'zjQlCbshk1A',
            events: { 'onReady': onPlayerReady }
        });
    }

    function onPlayerReady(event) {
        event.target.playVideo(); 
    }

    
    $(function () {
        var prox = $.connection.roomHub;


        var admin = '@admin';
        var id = '@id';
        var guid = '@Model.name';

        function init() {
            if (admin == id) {
                time = player.getDuration();
                prox.server.startInitCountDown(time, guid);
            } else {
                player.playVideo();
            }
        }

        prox.client.change = function (video) {
            player.loadVideoById(video);
            if (admin == id) {
                setTimeout(getTime, 2000);
            }
            document.getElementById("queueList").deleteRow(1);
        }

        function getTime() {
            time = player.getDuration();
            prox.server.countDown(time, guid);
        }

        $.connection.hub.start().done(init);
    });
</script>


<script>
    $('#searchButton').click(function search() {
        // Reset fields
        document.getElementById("vidUrl").value = "";
        document.getElementById("vidTitle").value = "";
        document.getElementById("searchError").innerHTML = "";
        document.getElementById("addVideo").disabled = true;

        // Load the query into the url
        var query = document.getElementById("searchQuery").value;

        if (query.length < 3 || query.length > 33) {
            document.getElementById("searchError").innerHTML = "Search queries must be 3-32 characters long!";
            return;
        }

        // requests JSON for query information
        var url = "https://www.googleapis.com/youtube/v3/search?videoEmbeddable=true&part=snippet&q=" + query + "&videoCaption=any&type=video&maxResults=1&key=AIzaSyAgKJngiP3aZa6HXQ8QnRMMgn83cy0UUK0";
        $.getJSON(url, function (data) {
            // length > 0 means there is a result. == 0 means garbage
            if (data.items.length > 0) {
                document.getElementById("vidUrl").value = "" + data.items[0].id.videoId;
                document.getElementById("vidTitle").value = "" + data.items[0].snippet.title;
                document.getElementById("searchError").innerHTML = "";
                document.getElementById("addVideo").disabled = false;
            }
            else {
                document.getElementById("searchError").innerHTML = "No search result found!";
            }
        });
    });
</script>

        

<!-- In browser search tests
<div id="qunit"></div>
<div id="qunit-fixture"></div>
<script src="~/Scripts/qunit-1.18.0.js"></script>
<script src="~/Scripts/searchtest.js"></script>
<!--
<script src="~/Scripts/queueTests.js"</script>
-->


<script>
    $(function () {
        //var chat = $.connection.chatHub;
        var tHub = $.connection.roomHub;
        //var roomName =
        tHub.client.addNewMessageToPage = function (name, message) {
            $('#discussion').append('<li><strong>' + htmlEncode(name)
                + '</strong>: ' + htmlEncode(message) + '</li>');
        };
        $('#message').focus();
        $.connection.hub.start().done(function () {
            $('#sendmessage').click(function () {
                tHub.server.send('@username', $('#message').val(), document.getElementById("roomName").innerHTML);
                $('#message').val('').focus();
            });
        });
    });
    function htmlEncode(value) {
        var encodedValue = $('<div />').text(value).html();
        return encodedValue;
    }
</script>

OurMusic/Views/Room/Edit.cshtml
@model OurMusic.Models.Room

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Room</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.roomid)

        <div class="form-group">
            @Html.LabelFor(model => model.isPrivate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isPrivate)
                @Html.ValidationMessageFor(model => model.isPrivate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.administrator, "administrator", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("administrator", String.Empty)
                @Html.ValidationMessageFor(model => model.administrator)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activeRoom, "activeRoom", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("activeRoom", String.Empty)
                @Html.ValidationMessageFor(model => model.activeRoom)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OurMusic/Views/Room/Index.cshtml
@model IEnumerable<OurMusic.Models.Room>

@{
    ViewBag.Title = "Index";
}



<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.isPrivate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person.firstName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.isPrivate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.firstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.roomid }) |
            @Html.ActionLink("Details", "Details", new { id=item.roomid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.roomid })
        </td>
    </tr>
}

</table>